/**
 * Component Examples
 * 
 * Generated by Doakumize Kit Generator
 * Date: 2025-11-11
 * 
 * Selected components: input, button
 */

window.ComponentExamples = {
  "input": {
    "title": "Input Components",
    "description": "",
    "items": [
      {
        "label": "입력 전 (default)",
        "code": "<div class=\"input-field\">\n  <input type=\"text\" class=\"input\" placeholder=\"입력 전\" />\n</div>"
      },
      {
        "label": "활성화 (focus)",
        "code": "<div class=\"input-field\">\n  <input type=\"text\" class=\"input\" value=\"활성화\" />\n</div>"
      },
      {
        "label": "입력 후 (filled)",
        "code": "<div class=\"input-field\">\n  <input type=\"text\" class=\"input\" value=\"입력 후\" />\n</div>"
      },
      {
        "label": "에러 (error)",
        "code": "<div class=\"input-field input-field--error\">\n  <input type=\"text\" class=\"input\" value=\"에러\" />\n</div>"
      },
      {
        "label": "비활성화 (disabled)",
        "code": "<div class=\"input-field\">\n  <input type=\"text\" class=\"input\" value=\"비활성화\" disabled />\n</div>"
      },
      {
        "label": "읽기전용 (readonly)",
        "code": "<div class=\"input-field\">\n  <input type=\"text\" class=\"input\" value=\"읽기전용\" readonly />\n</div>"
      },
      {
        "label": "medium + close",
        "code": "<div class=\"input-field input-field--with-close\">\n  <input type=\"text\" class=\"input\" placeholder=\"입력 전\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "medium + close (활성화)",
        "code": "<div class=\"input-field input-field--with-close\">\n  <input type=\"text\" class=\"input\" value=\"활성화\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "large + close",
        "code": "<div class=\"input-field input-field--large input-field--with-close\">\n  <input type=\"text\" class=\"input\" value=\"입력 후\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "error + close",
        "code": "<div class=\"input-field input-field--error input-field--with-close\">\n  <input type=\"text\" class=\"input\" value=\"에러\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "disabled + close",
        "code": "<div class=\"input-field input-field--with-close\">\n  <input type=\"text\" class=\"input\" value=\"비활성화\" disabled />\n  <button type=\"button\" class=\"input-addon input-addon--close\" disabled></button>\n</div>"
      },
      {
        "label": "readonly + close",
        "code": "<div class=\"input-field input-field--with-close\">\n  <input type=\"text\" class=\"input\" value=\"읽기전용\" readonly />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "small",
        "code": "<div class=\"input-field input-field--small\">\n  <input type=\"text\" class=\"input\" placeholder=\"Small 입력 필드\" />\n</div>"
      },
      {
        "label": "medium (기본)",
        "code": "<div class=\"input-field\">\n  <input type=\"text\" class=\"input\" placeholder=\"Medium 입력 필드\" />\n</div>"
      },
      {
        "label": "large",
        "code": "<div class=\"input-field input-field--large\">\n  <input type=\"text\" class=\"input\" placeholder=\"Large 입력 필드\" />\n</div>"
      },
      {
        "label": "small + close (16x16, 8px 간격)",
        "code": "<div class=\"input-field input-field--small input-field--with-close\">\n  <input type=\"text\" class=\"input\" value=\"Small with close\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "medium + close",
        "code": "<div class=\"input-field input-field--with-close\">\n  <input type=\"text\" class=\"input\" value=\"Medium with close\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "large + close",
        "code": "<div class=\"input-field input-field--large input-field--with-close\">\n  <input type=\"text\" class=\"input\" value=\"Large with close\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "medium + chip",
        "code": "<div class=\"input-field input-field--with-close input-field--with-chips\">\n  <div class=\"chip-group\">\n    <span class=\"chip chip--rounded\">\n      <span class=\"chip__text\">Chip</span>\n      <button type=\"button\" class=\"chip__remove\"></button>\n    </span>\n    <span class=\"chip chip--rounded\">\n      <span class=\"chip__text\">Chip</span>\n      <button type=\"button\" class=\"chip__remove\"></button>\n    </span>\n    <button class=\"chip chip--rounded chip--add\" type=\"button\"></button>\n  </div>\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "large + chip",
        "code": "<div class=\"input-field input-field--large input-field--with-close input-field--with-chips\">\n  <div class=\"chip-group\">\n    <span class=\"chip chip--rounded\">\n      <span class=\"chip__text\">Chip</span>\n      <button type=\"button\" class=\"chip__remove\"></button>\n    </span>\n    <span class=\"chip chip--rounded\">\n      <span class=\"chip__text\">Chip</span>\n      <button type=\"button\" class=\"chip__remove\"></button>\n    </span>\n    <button class=\"chip chip--rounded chip--add\" type=\"button\"></button>\n  </div>\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "기본 상태 (placeholder)",
        "code": "<div class=\"input-field input-field--with-counter\">\n  <textarea class=\"input\" rows=\"4\" maxlength=\"500\" placeholder=\"입력 전\"></textarea>\n  <span class=\"input-counter\">0/500</span>\n</div>"
      },
      {
        "label": "활성화 상태 (텍스트 입력됨)",
        "code": "<div class=\"input-field input-field--with-counter input-field--focused\">\n  <textarea class=\"input\" rows=\"4\" maxlength=\"500\">활성화</textarea>\n  <span class=\"input-counter\">3/500</span>\n</div>"
      },
      {
        "label": "입력 완료 상태",
        "code": "<div class=\"input-field input-field--with-counter\">\n  <textarea class=\"input\" rows=\"4\" maxlength=\"500\">입력 후</textarea>\n  <span class=\"input-counter\">4/500</span>\n</div>"
      },
      {
        "label": "기본 검색 (medium + close)",
        "code": "<div class=\"input-field input-field--search input-field--with-close\">\n  <i class=\"icon icon--medium icon--search\"></i>\n  <input type=\"search\" class=\"input\" placeholder=\"검색...\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "검색 (close 버튼 없음)",
        "code": "<div class=\"input-field input-field--search\">\n  <i class=\"icon icon--medium icon--search\"></i>\n  <input type=\"search\" class=\"input\" placeholder=\"검색...\" />\n</div>"
      },
      {
        "label": "검색 (입력 후)",
        "code": "<div class=\"input-field input-field--search input-field--with-close\">\n  <i class=\"icon icon--medium icon--search\"></i>\n  <input type=\"search\" class=\"input\" value=\"검색어 입력됨\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "small + close",
        "code": "<div class=\"input-field input-field--small input-field--search input-field--with-close\">\n  <i class=\"icon icon--small icon--search\"></i>\n  <input type=\"search\" class=\"input\" placeholder=\"검색...\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "large + close",
        "code": "<div class=\"input-field input-field--large input-field--search input-field--with-close\">\n  <i class=\"icon icon--large icon--search\"></i>\n  <input type=\"search\" class=\"input\" placeholder=\"검색...\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "error + close",
        "code": "<div class=\"input-field input-field--search input-field--error input-field--with-close\">\n  <i class=\"icon icon--medium icon--search\"></i>\n  <input type=\"search\" class=\"input\" value=\"잘못된 검색어\" />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      },
      {
        "label": "disabled + close",
        "code": "<div class=\"input-field input-field--search input-field--with-close\">\n  <i class=\"icon icon--medium icon--search\"></i>\n  <input type=\"search\" class=\"input\" value=\"비활성화\" disabled />\n  <button type=\"button\" class=\"input-addon input-addon--close\" disabled></button>\n</div>"
      },
      {
        "label": "readonly + close",
        "code": "<div class=\"input-field input-field--search input-field--with-close\">\n  <i class=\"icon icon--medium icon--search\"></i>\n  <input type=\"search\" class=\"input\" value=\"읽기전용\" readonly />\n  <button type=\"button\" class=\"input-addon input-addon--close\"></button>\n</div>"
      }
    ]
  },
  "button": {
    "title": "Button Components",
    "description": "",
    "items": [
      {
        "label": "primary / small",
        "code": "<button class=\"btn btn--primary btn--small\">Primary</button>"
      },
      {
        "label": "secondary / small",
        "code": "<button class=\"btn btn--secondary btn--small\">Secondary</button>"
      },
      {
        "label": "default / small",
        "code": "<button class=\"btn btn--default btn--small\">Default</button>"
      },
      {
        "label": "primary / medium",
        "code": "<button class=\"btn btn--primary btn--medium\">Primary</button>"
      },
      {
        "label": "secondary / medium",
        "code": "<button class=\"btn btn--secondary btn--medium\">Secondary</button>"
      },
      {
        "label": "default / medium",
        "code": "<button class=\"btn btn--default btn--medium\">Default</button>"
      },
      {
        "label": "primary / large",
        "code": "<button class=\"btn btn--primary btn--large\">Primary</button>"
      },
      {
        "label": "secondary / large",
        "code": "<button class=\"btn btn--secondary btn--large\">Secondary</button>"
      },
      {
        "label": "default / large",
        "code": "<button class=\"btn btn--default btn--large\">Default</button>"
      },
      {
        "label": "primary / disabled",
        "code": "<button class=\"btn btn--primary btn--disabled\" disabled>Disabled Primary</button>"
      },
      {
        "label": "secondary / disabled",
        "code": "<button class=\"btn btn--secondary btn--disabled\" disabled>Disabled Secondary</button>"
      },
      {
        "label": "default / disabled",
        "code": "<button class=\"btn btn--default btn--disabled\" disabled>Disabled Default</button>"
      },
      {
        "label": "medium / start icon",
        "code": "<button class=\"btn btn--primary btn--medium btn--start-icon\"><i class=\"icon icon--medium icon--plus\"></i>시작 아이콘</button>"
      },
      {
        "label": "medium / end icon",
        "code": "<button class=\"btn btn--secondary btn--medium btn--end-icon\">끝 아이콘<i class=\"icon icon--medium icon--arrow-right\"></i></button>"
      },
      {
        "label": "medium / only icon",
        "code": "<button class=\"btn btn--default btn--medium btn--only-icon\"><i class=\"icon icon--medium icon--check\"></i></button>"
      },
      {
        "label": "text / primary (underline)",
        "code": "<button class=\"btn btn--text\">텍스트 버튼</button>"
      },
      {
        "label": "text / secondary (underline)",
        "code": "<button class=\"btn btn--text btn--primary\">텍스트 버튼</button>"
      },
      {
        "label": "text / disabled",
        "code": "<button class=\"btn btn--text btn--disabled\" disabled>텍스트 버튼</button>"
      },
      {
        "label": "gradient / medium",
        "code": "<button class=\"btn btn--point btn--medium\">프라이머리 버튼</button>"
      },
      {
        "label": "gradient / disabled",
        "code": "<button class=\"btn btn--point btn--medium btn--disabled\" disabled>프라이머리 버튼</button>"
      }
    ]
  }
};