import PropTypes from "prop-types";

export const Icon = ({ name, size = "medium" }) => {
  return <i className={`icon icon--${size} icon--${name}`}></i>;
};

Icon.propTypes = {
  name: PropTypes.oneOf([
    // Arrow Icons
    "arrow-left",
    "arrow-right",
    "arrow-up",
    "arrow-down",
    "arrow-right-double",
    "arrow-left-double",
    "arrow-down-small",
    "arrow-up-small",
    "arrow-back",
    "arrow-back-end",
    "arrow-foward",
    "arrow-foward-end",
    // Common UI Icons
    "addpjt",
    "calendar",
    "close",
    "check",
    "check-default",
    "check-primary",
    "plus",
    "minus",
    "search",
    "edit",
    "edit-chip",
    "delete",
    "lnb",
    "lock",
    "trash",
    "settings",
    "more",
    "move",
    "play",
    "send",
    "save",
    "eye",
    // Info / Status Icons
    "info-circle",
    "info",
    "security",
    "key",
    // Message Icons
    "msg-confirm",
    "msg-confirm-in",
    "msg-error",
    "msg-info",
    "msg-success",
    "msg-warning",
    // Dropdown Icons
    "dropdown-arrow",
    "dropdown-check",
    "chevron-down",
    "chevron-up",
    "chevron-left",
    "chevron-right",
    // File Type Icons
    "file-attatch",
    "file-ppt",
    "file-outlook",
    "file-html",
    "file-pdf",
    "file-text",
    "file-image",
    "file-hangul",
    "file-excel",
    "file-word",
    "file-tool",
    "file-zip",
    "file-default",
    "file-doc",
    "file-xls",
    // App Specific Icons
    "dashboard",
    "code",
    "chart",
    "user",
    "members",
    "premium",
    "docbased",
    "webbased",
    "api-history",
    "aI-talk",
    "attached",
    "upload",
    "expanding",
    "folding",
    "rag-add",
    "rag-card",
    "rag-security",
    "copy",
    "good",
    "bad",
    "refresh",
    "pending",
    "chat-edit",
    "dictionary",
    "download",
    "external",
  ]),
};

Icon.defaultProps = {
  name: "icon",
};
